# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1.4
FROM python:3.12-slim

WORKDIR /app

# Install project dependencies
COPY pyproject.toml /app/
RUN pip install --no-cache-dir python-dotenv \
    && pip install --no-cache-dir .

# Copy source code
COPY . /app/

# Default: no ENTRYPOINT or CMD, commands will be injected by Smithery
